parameters:
    kunstmaan_template.template.manager.class: 'Kunstmaan\TemplateBundle\Helper\TemplateManager'
    kunstmaan_template.template.configuration.class: 'Kunstmaan\TemplateBundle\Helper\TemplateConfiguration'

services:
    kunstmaan_template.template.configuration:
        class: %kunstmaan_template.template.configuration.class%
        arguments:
          - %kunstmaan_template.templates%

    kunstmaan_template.template.manager:
        class: %kunstmaan_template.template.manager.class%
